language: python
env:
 - DJANGO_VERSION=1.8.15
 - DJANGO_VERSION=1.9.10
 - DJANGO_VERSION=1.10.3
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
 - pip install -q Django==$DJANGO_VERSION
script:
 - python runtests.py
