language: python
env:
 - DJANGO_VERSION=1.8.18
 - DJANGO_VERSION=1.9.13
 - DJANGO_VERSION=1.10.7
 - DJANGO_VERSION=1.11
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
 - pip install -q Django==$DJANGO_VERSION
script:
 - python runtests.py
